#define PIN_GSM_TX 0
#define PIN_GSM_RX 1

#define PIN_CRADLE 2

#define PIN_RING_STATE 6
#define PIN_RING_PULSE 7

#define PIN_ROTARY_DIAL_STATE 10
#define PIN_ROTARY_DIAL_PULSE 11

#define PIN_DIAL_IDLE_SOUND 14

#define ROTARY_DIAL_PULSE_RATE 100
#define AUTO_CALL_TIMEOUT 3000