#define DEBUG_GSM true
#define DEBUG_CRADLE true
#define DEBUG_ROTARY_DIAL true
#define DEBUG_AUTO_CALL true

#define PIN_CRADLE 2

#define PIN_RING_STATE 6
#define PIN_RING_PULSE 7
#define RING_AMOUNT 40
#define RING_PULSE_FREQ 25

#define PIN_IDLE_BEEP 10
#define PIN_SPEAKER_RELAIS_SET 11
#define PIN_SPEAKER_RELAIS_RESET 12

#define PIN_ROTARY_DIAL_STATE 14
#define PIN_ROTARY_DIAL_PULSE 15
#define ROTARY_DIAL_PULSE_FREQ 10

#define AUTO_CALL_TIMEOUT 3000
#define AUTO_CALL_MIN_NUMBER_LENGTH 6