#define DEBUG_GSM true
#define DEBUG_CRADLE true
#define DEBUG_ROTARY_DIAL true
#define DEBUG_AUTO_CALL true

#define PIN_CRADLE 2
#define CRADLE_HUNG_UP LOW
#define CRADLE_PICKED_UP !CRADLE_HUNG_UP

#define PIN_RING_STATE 6
#define PIN_RING_PULSE 7

#define PIN_ROTARY_DIAL_STATE 10
#define PIN_ROTARY_DIAL_PULSE 11
#define ROTARY_DIAL_PULSE_RATE 100

#define AUTO_CALL_TIMEOUT 3000
#define AUTO_CALL_MIN_NUMBER_LENGTH 6